import Head from "next/head";
import React, { useEffect } from "react";
import Col from "./Col";
import Navbar from "./Navbar";

interface ILayout {
  children: React.ReactNode;
}

const Layout = ({ children }: ILayout) => {
  return (
    <>
      <Col className="relative w-full h-full">
        <Head>
          <title>Pseudo Ecommerce Shop</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Navbar />
        <main className="overflow-x-hidden flex-grow flex flex-col py-4 bg-slate-100">
          {children}
        </main>
      </Col>
    </>
  );
};

export default Layout;
